version: '3'

services:
  tsc:
    image: 'node:14-alpine'
    volumes:
      - ../:/config-manager
    working_dir: /config-manager
    command: >
      sh -c "npm install typescript@^4.4.4 -g && npm i && tsc --watch"

  nodemon:
    image: 'node:14-alpine'
    volumes:
      - ../:/config-manager
      - ../.env:/config-manager/build/.env
      - ../secrets:/config-manager/build/secrets
      - ${CONFIG_PROTO_PATH}:/proto-files/ConfigStore/config.proto
    environment:
      - CONFIG_PROTO_PATH=/proto-files/ConfigStore/config.proto
    working_dir: /config-manager/build
    network_mode: host
    command: >
      sh -c "npm install nodemon -g && nodemon app.js"