version: '3'

services:
  tsc:
    image: 'node:14.18.0-alpine3.14'
    volumes:
      - .:/app
    working_dir: /app
    command: >
      sh -c "npm install typescript@^4.4.3 -g
      && tsc --watch"

  server:
    image: 'node:14.18.0-alpine3.14'
    volumes:
      - .:/app
      - ${PROTO_FILES_PATH}:/proto-files
    working_dir: /app
    network_mode: host
    command: >
      sh -c "npm i nodemon -g
      && nodemon build/testHydra.js"